# backend/alembic/versions/2025_12_04_1000_add_user_preferences.py
"""Add user preferences to user_profiles table

Revision ID: 2025_12_04_1000
Revises: <previous_revision_id>
Create Date: 2025-12-04 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # Import for array type

# revision identifiers, used by Alembic.
revision = '2025_12_04_1000'
down_revision = '<previous_revision_id>' # Replace with actual previous revision ID
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('fitness_goal', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('dietary_preferences', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('user_profiles', sa.Column('fitness_persona', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'fitness_persona')
    op.drop_column('user_profiles', 'dietary_preferences')
    op.drop_column('user_profiles', 'fitness_goal')
    # ### end Alembic commands ###
