"""Create workout_logs table

Revision ID: 2025_12_04_1200
Revises: 2025_12_04_1100
Create Date: 2025-12-04 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid # Needed for default UUID generation

# revision identifiers, used by Alembic.
revision = '2025_12_04_1200'
down_revision = '2025_12_04_1100'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'workout_logs',
        sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True, default=sa.text('uuid_generate_v4()')),
        sa.Column('user_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('users.id'), nullable=False),
        sa.Column('workout_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('workout_plans.id'), nullable=True),
        sa.Column('status', sa.Enum('completed', 'skipped', 'partial', name='workout_status'), nullable=False),
        sa.Column('difficulty_rating', sa.Integer(), nullable=True),
        sa.Column('duration_minutes', sa.Integer(), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('logged_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_logs_id'), 'workout_logs', ['id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_workout_id'), 'workout_logs', ['workout_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_logs_workout_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_id'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.execute("DROP TYPE workout_status") # Drop the enum type as well
    # ### end Alembic commands ###
